openapi: 3.0.0
info:
  title: NetSchool
  description: The API for the NetSchool irTech project
  version: 5.10.63221
servers:
- url: https://virtserver.swaggerhub.com/LEBEDEVKM/NetSchool/5.10.63221
  description: SwaggerHub API Auto Mocking
security:
- bearerAuth: []
paths:
  /mysettings:
    get:
      tags:
      - mysettings
      description: returns my settings
      operationId: mysettings
      parameters:
      - name: at
        in: header
        description: an authorization header
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: All my settings
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/mySettings'
  /mysettings/yearlist:
    get:
      tags:
      - mysettings
      description: returns all years
      operationId: yearlist
      parameters:
      - name: at
        in: header
        description: an authorization header
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: All the years
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/mySettingsYears'
  /grade/assignment/types:
    get:
      tags:
      - assignment
      description: returns all assignment types
      operationId: assignmentTypes
      responses:
        "200":
          description: All the assignment types
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/assignmentTypes'
  /student/diary/init:
    get:
      tags:
      - student
      description: returns strudent diary init data
      operationId: studentDiaryInit
      responses:
        "200":
          description: Init data the strudent diary
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/studentDiaryInit'
  /student/diary:
    get:
      tags:
      - student
      description: returns all assignments
      operationId: studentDiary
      parameters:
      - name: studentId
        in: query
        required: true
        style: form
        explode: true
        schema:
          type: integer
      - name: weekStart
        in: query
        required: false
        style: form
        explode: true
        schema:
          type: string
          format: date
      - name: weekEnd
        in: query
        required: false
        style: form
        explode: true
        schema:
          type: string
          format: date
      - name: withLaAssigns
        in: query
        required: false
        style: form
        explode: true
        schema:
          type: boolean
      - name: withPastMandatory
        in: query
        required: false
        style: form
        explode: true
        schema:
          type: boolean
      - name: yearId
        in: query
        required: false
        style: form
        explode: true
        schema:
          type: integer
      responses:
        "200":
          description: All the prepareloginform
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Diary'
  /student/diary/assigns/{assignId}:
    get:
      tags:
      - diary
      description: returns assign information
      operationId: diaryAssignnDetails
      parameters:
      - name: assignId
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: integer
      - name: studentId
        in: query
        required: true
        style: form
        explode: true
        schema:
          type: integer
      responses:
        "200":
          description: Details about assign
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/diaryAssignDetails'
  /auth/getdata:
    post:
      tags:
      - login
      description: returns all login data
      operationId: getauthdata
      responses:
        "200":
          description: All the login data
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetAuthData'
      security: []
  /login:
    post:
      tags:
      - login
      description: returns all login data
      operationId: login
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/login_body'
        required: true
      responses:
        "200":
          description: All the login data
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Login'
      security: []
  /logindata:
    get:
      tags:
      - login
      description: returns all login data
      operationId: logindata
      responses:
        "200":
          description: All the login data
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoginData'
      security: []
  /loginform:
    get:
      tags:
      - login
      description: returns all loginform
      operationId: loginform
      parameters:
      - name: cid
        in: query
        required: false
        style: form
        explode: true
        schema:
          type: integer
      - name: sid
        in: query
        required: false
        style: form
        explode: true
        schema:
          type: integer
      - name: pid
        in: query
        required: false
        style: form
        explode: true
        schema:
          type: integer
      - name: cn
        in: query
        required: false
        style: form
        explode: true
        schema:
          type: integer
      - name: sft
        in: query
        required: false
        style: form
        explode: true
        schema:
          type: integer
      - name: LASTNAME
        in: query
        required: false
        style: form
        explode: true
        schema:
          type: string
      - name: cacheVer
        in: query
        required: false
        style: form
        explode: true
        schema:
          type: string
      responses:
        "200":
          description: All the LoginForm
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoginForm'
      security: []
  /prepareloginform:
    get:
      tags:
      - login
      description: returns all prepareloginform
      operationId: prepareloginform
      parameters:
      - name: cid
        in: query
        required: false
        style: form
        explode: true
        schema:
          type: integer
      - name: sid
        in: query
        required: false
        style: form
        explode: true
        schema:
          type: integer
      - name: pid
        in: query
        required: false
        style: form
        explode: true
        schema:
          type: integer
      - name: cn
        in: query
        required: false
        style: form
        explode: true
        schema:
          type: integer
      - name: sft
        in: query
        required: false
        style: form
        explode: true
        schema:
          type: integer
      - name: LASTNAME
        in: query
        required: false
        style: form
        explode: true
        schema:
          type: string
      - name: cacheVer
        in: query
        required: false
        style: form
        explode: true
        schema:
          type: string
      responses:
        "200":
          description: All the prepareloginform
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PrepareLoginForm'
      security: []
  /prepareemloginform:
    get:
      tags:
      - login
      description: returns all prepareemloginform
      operationId: prepareemloginform
      parameters:
      - name: cacheVer
        in: query
        required: false
        style: form
        explode: true
        schema:
          type: string
      responses:
        "200":
          description: All the prepareemloginform
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PrepareEmLoginForm'
      security: []
components:
  schemas:
    GetAuthData:
      type: object
      properties:
        lt:
          type: string
          example: "1073163840"
        ver:
          type: string
          example: "768253229"
        salt:
          type: string
          example: "1458933352"
      example:
        ver: "768253229"
        salt: "1458933352"
        lt: "1073163840"
    Login:
      type: object
      properties:
        at:
          type: string
          example: "00168638015429814024329375"
        code:
          type: string
        timeOut:
          type: integer
          example: 900000
        accessToken:
          type: string
        refreshToken:
          type: string
        accountInfo:
          $ref: '#/components/schemas/Login_accountInfo'
        tokenType:
          type: string
          example: Bearer
        entryPoint:
          type: string
          example: /asp/SecurityWarning.asp
        requestData:
          $ref: '#/components/schemas/Login_requestData'
        errorMessage:
          type: string
      example:
        accountInfo:
          userRoles:
            role:
              name: Родитель
              id: 2
            schoolId: 22
            userId: 70111
          canLogin: true
          loginTime: 2000-01-23
          secureActiveToken: secureActiveToken
          organizations:
          - name: 'МБОУ СОШ №19 (г. Екатеринбург) '
            id: 22
          - name: 'МБОУ СОШ №19 (г. Екатеринбург) '
            id: 22
          active: true
          currentOrganization:
            name: МБОУ СОШ №19
            id: 22
          activeToken: activeToken
          storeTokens: true
          accessToken: "00168638015429814024329375"
          user:
            name: Иванов И. И.
            id: 70111
        at: "00168638015429814024329375"
        code: code
        errorMessage: errorMessage
        entryPoint: /asp/SecurityWarning.asp
        accessToken: accessToken
        tokenType: Bearer
        requestData:
          warnType: "1"
        timeOut: 900000
        refreshToken: refreshToken
    mySettingsYears:
      type: array
      items:
        $ref: '#/components/schemas/mySettingsYears_inner'
      x-schema-name: mySettingsYears
    mySettings:
      type: object
      properties:
        userId:
          type: integer
          example: 0
        firstName:
          type: string
          example: Иван
        lastName:
          type: string
          example: Иванов
        middleName:
          type: string
          example: Иванович
        loginName:
          type: string
          example: ИвановИИ
        birthDate:
          type: string
          format: date
        roles:
          type: array
          items:
            type: string
            example: Parent
        schoolyearId:
          type: integer
          example: 0
        windowsAccount:
          type: string
          example: ""
        mobilePhone:
          type: string
          example: "79926155431"
        preferedCom:
          type: string
          example: C
        email:
          type: string
          example: ivanov@mail.ru
        existsPhoto:
          type: boolean
          example: false
        userSettings:
          $ref: '#/components/schemas/mySettings_userSettings'
      example:
        lastName: Иванов
        roles:
        - Parent
        - Parent
        preferedCom: C
        userId: 0
        birthDate: 2000-01-23
        firstName: Иван
        userSettings:
          recoveryAnswer: 32ecd387055d5b01d8e7ac7fef380eb1
          defaultDesktop: 0
          language: ru
          theme: 0
          favoriteReports:
          - favoriteReports
          - favoriteReports
          recoveryQuestion: Девичья фамилия вашей матери
          passwordExpired: 0
          userId: 70111
          showNetSchoolApp: true
          showMobilePhone: true
        mobilePhone: "79926155431"
        windowsAccount: ""
        loginName: ИвановИИ
        schoolyearId: 0
        middleName: Иванович
        email: ivanov@mail.ru
        existsPhoto: false
    diaryAssignDetails:
      type: object
      properties:
        id:
          type: integer
          example: 5111111
        assignmentName:
          type: string
          example: Развитие речи. Сочинение-рассуждение по рассказу «Коллекционная
            вещь» Тибора Фишера
        activityName:
          type: string
          example: nil
        problemName:
          type: string
          example: nil
        subjectGroup:
          $ref: '#/components/schemas/diaryAssignDetails_subjectGroup'
        teachers:
          type: array
          items:
            $ref: '#/components/schemas/diaryAssignDetails_teachers'
        productId:
          type: integer
        isDeleted:
          type: boolean
          example: false
        weight:
          type: integer
          example: 10
        date:
          type: string
          format: date
        description:
          type: string
          example: Задание по рядам - рассуждение по картине. Смотрите прикреплённый
            файл
        attachments:
          type: array
          items:
            $ref: '#/components/schemas/diaryAssignDetails_attachments'
        contentElements:
          type: array
          example: nil
          items:
            type: object
        codeContentElements:
          type: array
          example: nil
          items:
            type: object
      example:
        date: 2000-01-23
        attachments:
        - originalFileName: Дз 5К.doc
          name: Дз 5К.doc
          description: nil
          id: 1111
        - originalFileName: Дз 5К.doc
          name: Дз 5К.doc
          description: nil
          id: 1111
        productId: 0
        subjectGroup:
          name: 5ж/Русский язык
          id: 171111
        contentElements: nil
        activityName: nil
        weight: 10
        description: Задание по рядам - рассуждение по картине. Смотрите прикреплённый
          файл
        problemName: nil
        isDeleted: false
        teachers:
        - name: Иванова Марья Ивановна
          id: 71111
        - name: Иванова Марья Ивановна
          id: 71111
        codeContentElements: nil
        id: 5111111
        assignmentName: Развитие речи. Сочинение-рассуждение по рассказу «Коллекционная
          вещь» Тибора Фишера
    studentDiaryInit:
      type: object
      properties:
        students:
          type: array
          items:
            $ref: '#/components/schemas/studentDiaryInit_students'
        currentStudentId:
          type: integer
          example: 1111
        weekStart:
          type: string
          format: date
        yaClass:
          type: boolean
          example: false
        yaClassAuthUrl:
          type: string
          example: http://www.yaklass.ru/Account/NetSchoolGate?server=http%3a%2f%2fnetcity.ru%2f&ns_token=999999999999&ts=1662877853&nn=417563999&sg=7-JyisFQvEp_ayPSXfp_PpfCd0o1
        newDiskToken:
          type: string
          example: ""
        newDiskWasRequest:
          type: boolean
          example: false
        ttsuRl:
          type: string
          example: http://NETCITY:80/
        externalUrl:
          type: string
          example: http://netcity.ru/
        weight:
          type: boolean
          example: false
        maxMark:
          type: integer
          example: 5
        withLaAssigns:
          type: boolean
          example: true
      example:
        externalUrl: http://netcity.ru/
        weekStart: 2000-01-23
        currentStudentId: 1111
        newDiskWasRequest: false
        ttsuRl: http://NETCITY:80/
        students:
        - studentId: 1111
          classId: 0
          iupGrade: 0
          nickName: Иванов Иван
          className: nil
        - studentId: 1111
          classId: 0
          iupGrade: 0
          nickName: Иванов Иван
          className: nil
        weight: false
        yaClass: false
        yaClassAuthUrl: http://www.yaklass.ru/Account/NetSchoolGate?server=http%3a%2f%2fnetcity.ru%2f&ns_token=999999999999&ts=1662877853&nn=417563999&sg=7-JyisFQvEp_ayPSXfp_PpfCd0o1
        maxMark: 5
        newDiskToken: ""
        withLaAssigns: true
    assignmentTypes:
      type: array
      items:
        $ref: '#/components/schemas/assignmentTypes_inner'
      x-schema-name: assignmentTypes
    Mark:
      type: object
      properties:
        assignmentId:
          type: integer
        studentId:
          type: integer
        mark:
          type: integer
        dutyMark:
          type: boolean
      example:
        studentId: 1
        assignmentId: 6
        dutyMark: true
        mark: 5
    Attachment:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        originalFileName:
          type: string
        description:
          type: string
      example:
        originalFileName: originalFileName
        name: name
        description: description
        id: 5
    DiaryAssignment:
      type: object
      properties:
        mark:
          $ref: '#/components/schemas/Mark'
        attachments:
          type: array
          items:
            $ref: '#/components/schemas/Attachment'
        id:
          type: integer
        typeId:
          type: integer
        assignmentName:
          type: string
        weight:
          type: integer
        dueDate:
          type: string
          format: date
        classMeetingId:
          type: integer
        existsTestPlan:
          type: boolean
      example:
        existsTestPlan: true
        attachments:
        - originalFileName: originalFileName
          name: name
          description: description
          id: 5
        - originalFileName: originalFileName
          name: name
          description: description
          id: 5
        dueDate: 2000-01-23
        weight: 9
        typeId: 7
        classMeetingId: 3
        id: 2
        mark:
          studentId: 1
          assignmentId: 6
          dutyMark: true
          mark: 5
        assignmentName: assignmentName
    DiaryLesson:
      type: object
      properties:
        classmeetingId:
          type: string
        day:
          type: string
          format: date
        number:
          type: integer
        room:
          type: string
        startTime:
          type: string
        endTime:
          type: string
        subjectName:
          type: string
        assignments:
          type: array
          items:
            $ref: '#/components/schemas/DiaryAssignment'
      example:
        number: 0
        assignments:
        - existsTestPlan: true
          attachments:
          - originalFileName: originalFileName
            name: name
            description: description
            id: 5
          - originalFileName: originalFileName
            name: name
            description: description
            id: 5
          dueDate: 2000-01-23
          weight: 9
          typeId: 7
          classMeetingId: 3
          id: 2
          mark:
            studentId: 1
            assignmentId: 6
            dutyMark: true
            mark: 5
          assignmentName: assignmentName
        - existsTestPlan: true
          attachments:
          - originalFileName: originalFileName
            name: name
            description: description
            id: 5
          - originalFileName: originalFileName
            name: name
            description: description
            id: 5
          dueDate: 2000-01-23
          weight: 9
          typeId: 7
          classMeetingId: 3
          id: 2
          mark:
            studentId: 1
            assignmentId: 6
            dutyMark: true
            mark: 5
          assignmentName: assignmentName
        startTime: startTime
        endTime: endTime
        classmeetingId: classmeetingId
        day: 2000-01-23
        room: room
        subjectName: subjectName
    DiaryWeekDays:
      type: object
      properties:
        date:
          type: string
          format: date
        lessons:
          type: array
          items:
            $ref: '#/components/schemas/DiaryLesson'
      example:
        date: 2000-01-23
        lessons:
        - number: 0
          assignments:
          - existsTestPlan: true
            attachments:
            - originalFileName: originalFileName
              name: name
              description: description
              id: 5
            - originalFileName: originalFileName
              name: name
              description: description
              id: 5
            dueDate: 2000-01-23
            weight: 9
            typeId: 7
            classMeetingId: 3
            id: 2
            mark:
              studentId: 1
              assignmentId: 6
              dutyMark: true
              mark: 5
            assignmentName: assignmentName
          - existsTestPlan: true
            attachments:
            - originalFileName: originalFileName
              name: name
              description: description
              id: 5
            - originalFileName: originalFileName
              name: name
              description: description
              id: 5
            dueDate: 2000-01-23
            weight: 9
            typeId: 7
            classMeetingId: 3
            id: 2
            mark:
              studentId: 1
              assignmentId: 6
              dutyMark: true
              mark: 5
            assignmentName: assignmentName
          startTime: startTime
          endTime: endTime
          classmeetingId: classmeetingId
          day: 2000-01-23
          room: room
          subjectName: subjectName
        - number: 0
          assignments:
          - existsTestPlan: true
            attachments:
            - originalFileName: originalFileName
              name: name
              description: description
              id: 5
            - originalFileName: originalFileName
              name: name
              description: description
              id: 5
            dueDate: 2000-01-23
            weight: 9
            typeId: 7
            classMeetingId: 3
            id: 2
            mark:
              studentId: 1
              assignmentId: 6
              dutyMark: true
              mark: 5
            assignmentName: assignmentName
          - existsTestPlan: true
            attachments:
            - originalFileName: originalFileName
              name: name
              description: description
              id: 5
            - originalFileName: originalFileName
              name: name
              description: description
              id: 5
            dueDate: 2000-01-23
            weight: 9
            typeId: 7
            classMeetingId: 3
            id: 2
            mark:
              studentId: 1
              assignmentId: 6
              dutyMark: true
              mark: 5
            assignmentName: assignmentName
          startTime: startTime
          endTime: endTime
          classmeetingId: classmeetingId
          day: 2000-01-23
          room: room
          subjectName: subjectName
    Diary:
      type: object
      properties:
        weekStart:
          type: string
        weekEnd:
          type: string
        weekDays:
          type: array
          items:
            $ref: '#/components/schemas/DiaryWeekDays'
        termName:
          type: string
        className:
          type: string
      example:
        weekStart: weekStart
        weekDays:
        - date: 2000-01-23
          lessons:
          - number: 0
            assignments:
            - existsTestPlan: true
              attachments:
              - originalFileName: originalFileName
                name: name
                description: description
                id: 5
              - originalFileName: originalFileName
                name: name
                description: description
                id: 5
              dueDate: 2000-01-23
              weight: 9
              typeId: 7
              classMeetingId: 3
              id: 2
              mark:
                studentId: 1
                assignmentId: 6
                dutyMark: true
                mark: 5
              assignmentName: assignmentName
            - existsTestPlan: true
              attachments:
              - originalFileName: originalFileName
                name: name
                description: description
                id: 5
              - originalFileName: originalFileName
                name: name
                description: description
                id: 5
              dueDate: 2000-01-23
              weight: 9
              typeId: 7
              classMeetingId: 3
              id: 2
              mark:
                studentId: 1
                assignmentId: 6
                dutyMark: true
                mark: 5
              assignmentName: assignmentName
            startTime: startTime
            endTime: endTime
            classmeetingId: classmeetingId
            day: 2000-01-23
            room: room
            subjectName: subjectName
          - number: 0
            assignments:
            - existsTestPlan: true
              attachments:
              - originalFileName: originalFileName
                name: name
                description: description
                id: 5
              - originalFileName: originalFileName
                name: name
                description: description
                id: 5
              dueDate: 2000-01-23
              weight: 9
              typeId: 7
              classMeetingId: 3
              id: 2
              mark:
                studentId: 1
                assignmentId: 6
                dutyMark: true
                mark: 5
              assignmentName: assignmentName
            - existsTestPlan: true
              attachments:
              - originalFileName: originalFileName
                name: name
                description: description
                id: 5
              - originalFileName: originalFileName
                name: name
                description: description
                id: 5
              dueDate: 2000-01-23
              weight: 9
              typeId: 7
              classMeetingId: 3
              id: 2
              mark:
                studentId: 1
                assignmentId: 6
                dutyMark: true
                mark: 5
              assignmentName: assignmentName
            startTime: startTime
            endTime: endTime
            classmeetingId: classmeetingId
            day: 2000-01-23
            room: room
            subjectName: subjectName
        - date: 2000-01-23
          lessons:
          - number: 0
            assignments:
            - existsTestPlan: true
              attachments:
              - originalFileName: originalFileName
                name: name
                description: description
                id: 5
              - originalFileName: originalFileName
                name: name
                description: description
                id: 5
              dueDate: 2000-01-23
              weight: 9
              typeId: 7
              classMeetingId: 3
              id: 2
              mark:
                studentId: 1
                assignmentId: 6
                dutyMark: true
                mark: 5
              assignmentName: assignmentName
            - existsTestPlan: true
              attachments:
              - originalFileName: originalFileName
                name: name
                description: description
                id: 5
              - originalFileName: originalFileName
                name: name
                description: description
                id: 5
              dueDate: 2000-01-23
              weight: 9
              typeId: 7
              classMeetingId: 3
              id: 2
              mark:
                studentId: 1
                assignmentId: 6
                dutyMark: true
                mark: 5
              assignmentName: assignmentName
            startTime: startTime
            endTime: endTime
            classmeetingId: classmeetingId
            day: 2000-01-23
            room: room
            subjectName: subjectName
          - number: 0
            assignments:
            - existsTestPlan: true
              attachments:
              - originalFileName: originalFileName
                name: name
                description: description
                id: 5
              - originalFileName: originalFileName
                name: name
                description: description
                id: 5
              dueDate: 2000-01-23
              weight: 9
              typeId: 7
              classMeetingId: 3
              id: 2
              mark:
                studentId: 1
                assignmentId: 6
                dutyMark: true
                mark: 5
              assignmentName: assignmentName
            - existsTestPlan: true
              attachments:
              - originalFileName: originalFileName
                name: name
                description: description
                id: 5
              - originalFileName: originalFileName
                name: name
                description: description
                id: 5
              dueDate: 2000-01-23
              weight: 9
              typeId: 7
              classMeetingId: 3
              id: 2
              mark:
                studentId: 1
                assignmentId: 6
                dutyMark: true
                mark: 5
              assignmentName: assignmentName
            startTime: startTime
            endTime: endTime
            classmeetingId: classmeetingId
            day: 2000-01-23
            room: room
            subjectName: subjectName
        weekEnd: weekEnd
        className: className
        termName: termName
    PrepareEmLoginForm:
      type: object
      properties:
        countries:
          type: array
          items:
            $ref: '#/components/schemas/PrepareEmLoginForm_countries'
        states:
          type: array
          items:
            $ref: '#/components/schemas/PrepareEmLoginForm_countries'
        hlevels:
          type: array
          items:
            $ref: '#/components/schemas/PrepareEmLoginForm_countries'
        ems:
          type: array
          items:
            $ref: '#/components/schemas/PrepareEmLoginForm_countries'
        em_cid:
          type: integer
        em_sid:
          type: integer
        hlevel:
          type: integer
        emId:
          type: integer
      example:
        em_cid: 0
        em_sid: 6
        hlevel: 1
        ems:
        - null
        - null
        countries:
        - name: name
          id: 0
        - name: name
          id: 0
        emId: 5
        hlevels:
        - null
        - null
        states:
        - null
        - null
    PrepareLoginForm:
      type: object
      properties:
        countries:
          type: array
          items:
            $ref: '#/components/schemas/PrepareEmLoginForm_countries'
        states:
          type: array
          items:
            $ref: '#/components/schemas/PrepareEmLoginForm_countries'
        provinces:
          type: array
          items:
            $ref: '#/components/schemas/PrepareEmLoginForm_countries'
        cities:
          type: array
          items:
            $ref: '#/components/schemas/PrepareEmLoginForm_countries'
        funcs:
          type: array
          items:
            $ref: '#/components/schemas/PrepareEmLoginForm_countries'
        schools:
          type: array
          items:
            $ref: '#/components/schemas/PrepareEmLoginForm_countries'
        cid:
          type: integer
        sid:
          type: integer
        pid:
          type: integer
        cn:
          type: integer
        sft:
          type: integer
        scid:
          type: integer
        hlevels:
          type: object
        ems:
          type: object
      example:
        sft: 5
        provinces:
        - null
        - null
        cities:
        - null
        - null
        pid: 1
        ems: {}
        countries:
        - name: name
          id: 0
        - name: name
          id: 0
        cn: 5
        hlevels: {}
        states:
        - null
        - null
        sid: 6
        schools:
        - null
        - null
        funcs:
        - null
        - null
        scid: 2
        cid: 0
    LoginForm:
      type: object
      properties:
        items:
          type: array
          items:
            $ref: '#/components/schemas/PrepareEmLoginForm_countries'
        lastElem:
          type: string
      example:
        lastElem: lastElem
        items:
        - name: name
          id: 0
        - name: name
          id: 0
    LoginData:
      type: object
      properties:
        productName:
          type: string
        version:
          type: string
        schoolLogin:
          type: boolean
        emLogin:
          type: boolean
        esiaLogin:
          type: boolean
        esiaLoginPage:
          type: string
        esiaMainAuth:
          type: boolean
        esiaButton:
          type: boolean
        signatureLogin:
          type: boolean
        cacheVer:
          type: string
        windowsAuth:
          type: boolean
        enableSms:
          type: boolean
        esaLogin:
          type: boolean
        esaLoginPage:
          type: string
      example:
        schoolLogin: true
        esiaLoginPage: esiaLoginPage
        cacheVer: cacheVer
        windowsAuth: true
        version: version
        productName: productName
        esiaButton: true
        enableSms: true
        signatureLogin: true
        esiaMainAuth: true
        emLogin: true
        esaLoginPage: esaLoginPage
        esaLogin: true
        esiaLogin: true
    login_body:
      type: object
      properties:
        LoginType:
          type: integer
          example: 1
        cid:
          type: integer
          example: 2
        sid:
          type: integer
          example: 66
        pid:
          type: integer
          example: -1
        cn:
          type: integer
          example: 3
        sft:
          type: integer
          example: 2
        scid:
          type: integer
          example: 22
        UN:
          type: string
          example: ИвановИИ
        PW:
          type: string
          example: 913c33
        lt:
          type: integer
          example: 728627461
        pw2:
          type: string
          example: 913c329378a9055fed2d7cb971012ab9
        ver:
          type: integer
          example: 768250818
    Login_accountInfo_currentOrganization:
      type: object
      properties:
        id:
          type: integer
          example: 22
        name:
          type: string
          example: МБОУ СОШ №19
      example:
        name: МБОУ СОШ №19
        id: 22
    Login_accountInfo_user:
      type: object
      properties:
        id:
          type: integer
          example: 70111
        name:
          type: string
          example: Иванов И. И.
      example:
        name: Иванов И. И.
        id: 70111
    Login_accountInfo_userRoles_role:
      type: object
      properties:
        id:
          type: integer
          example: 2
        name:
          type: string
          example: Родитель
      example:
        name: Родитель
        id: 2
    Login_accountInfo_userRoles:
      type: object
      properties:
        userId:
          type: integer
          example: 70111
        schoolId:
          type: integer
          example: 22
        role:
          $ref: '#/components/schemas/Login_accountInfo_userRoles_role'
      example:
        role:
          name: Родитель
          id: 2
        schoolId: 22
        userId: 70111
    Login_accountInfo_organizations:
      type: object
      properties:
        id:
          type: integer
          example: 22
        name:
          type: string
          example: 'МБОУ СОШ №19 (г. Екатеринбург) '
      example:
        name: 'МБОУ СОШ №19 (г. Екатеринбург) '
        id: 22
    Login_accountInfo:
      type: object
      properties:
        activeToken:
          type: string
        secureActiveToken:
          type: string
        currentOrganization:
          $ref: '#/components/schemas/Login_accountInfo_currentOrganization'
        user:
          $ref: '#/components/schemas/Login_accountInfo_user'
        userRoles:
          $ref: '#/components/schemas/Login_accountInfo_userRoles'
        organizations:
          type: array
          items:
            $ref: '#/components/schemas/Login_accountInfo_organizations'
        loginTime:
          type: string
          format: date
        active:
          type: boolean
          example: true
        canLogin:
          type: boolean
          example: true
        storeTokens:
          type: boolean
          example: true
        accessToken:
          type: string
          example: "00168638015429814024329375"
      example:
        userRoles:
          role:
            name: Родитель
            id: 2
          schoolId: 22
          userId: 70111
        canLogin: true
        loginTime: 2000-01-23
        secureActiveToken: secureActiveToken
        organizations:
        - name: 'МБОУ СОШ №19 (г. Екатеринбург) '
          id: 22
        - name: 'МБОУ СОШ №19 (г. Екатеринбург) '
          id: 22
        active: true
        currentOrganization:
          name: МБОУ СОШ №19
          id: 22
        activeToken: activeToken
        storeTokens: true
        accessToken: "00168638015429814024329375"
        user:
          name: Иванов И. И.
          id: 70111
    Login_requestData:
      type: object
      properties:
        warnType:
          type: string
          example: "1"
      example:
        warnType: "1"
    mySettingsYears_inner:
      type: object
      properties:
        id:
          type: integer
          example: 24
        name:
          type: string
          example: (*) 2011/2012
      example:
        name: (*) 2011/2012
        id: 24
    mySettings_userSettings:
      type: object
      properties:
        showMobilePhone:
          type: boolean
          example: true
        defaultDesktop:
          type: integer
          example: 0
        language:
          type: string
          example: ru
        favoriteReports:
          type: array
          items:
            type: string
        passwordExpired:
          type: integer
          example: 0
        recoveryAnswer:
          type: string
          example: 32ecd387055d5b01d8e7ac7fef380eb1
        recoveryQuestion:
          type: string
          example: Девичья фамилия вашей матери
        theme:
          type: integer
          example: 0
        userId:
          type: integer
          example: 70111
        showNetSchoolApp:
          type: boolean
          example: true
      example:
        recoveryAnswer: 32ecd387055d5b01d8e7ac7fef380eb1
        defaultDesktop: 0
        language: ru
        theme: 0
        favoriteReports:
        - favoriteReports
        - favoriteReports
        recoveryQuestion: Девичья фамилия вашей матери
        passwordExpired: 0
        userId: 70111
        showNetSchoolApp: true
        showMobilePhone: true
    diaryAssignDetails_subjectGroup:
      type: object
      properties:
        id:
          type: integer
          example: 171111
        name:
          type: string
          example: 5ж/Русский язык
      example:
        name: 5ж/Русский язык
        id: 171111
    diaryAssignDetails_teachers:
      type: object
      properties:
        id:
          type: integer
          example: 71111
        name:
          type: string
          example: Иванова Марья Ивановна
      example:
        name: Иванова Марья Ивановна
        id: 71111
    diaryAssignDetails_attachments:
      type: object
      properties:
        id:
          type: integer
          example: 1111
        name:
          type: string
          example: Дз 5К.doc
        originalFileName:
          type: string
          example: Дз 5К.doc
        description:
          type: string
          example: nil
      example:
        originalFileName: Дз 5К.doc
        name: Дз 5К.doc
        description: nil
        id: 1111
    studentDiaryInit_students:
      type: object
      properties:
        studentId:
          type: integer
          example: 1111
        nickName:
          type: string
          example: Иванов Иван
        className:
          type: object
          example: nil
        classId:
          type: integer
          example: 0
        iupGrade:
          type: integer
          example: 0
      example:
        studentId: 1111
        classId: 0
        iupGrade: 0
        nickName: Иванов Иван
        className: nil
    assignmentTypes_inner:
      type: object
      properties:
        abbr:
          type: string
          example: ДЗ
        order:
          type: integer
          example: 15
        id:
          type: integer
          example: 3
        name:
          type: string
          example: Домашнее задание
      example:
        name: Домашнее задание
        id: 3
        abbr: ДЗ
        order: 15
    PrepareEmLoginForm_countries:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
      example:
        name: name
        id: 0
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
